### PR TITLE
added electronVolt_num to permit plotting with matplotlib

### PR DESCRIPTION
**Pull request by jguterl**
Added a version without objectification of units to run calculations with values of fundamental qqty (e.g. electronvolt) and plot results with matplotlib. 
```
import electronvolt_num  as units
plt.plot(1*units.eV)
```
Suggestion:
develop electronvolt_CSG and electronvolt_CSGnum with CSG units 
and electronvolt_SI and electronvolt_SInum

### CODE REVIEW

**Comment by dw61** [comment]
Could you explain why do we want to plot a unit as a float in matplotlib? And as an alternative, would it be better to implement a function that force convert `Quantity` objects to `float`?

**Comment by dw61** [comment]
> Could you explain why do we want to plot a unit as a float in matplotlib? And as an alternative, would it be better to implement a function that force convert `Quantity` objects to `float`?

I just found out that it seems you can access the `float` type value of a `Quantity` object by directly accessing the `value` field, e.g. `plt.plot(eV.value)`. Is that what we want?

**Comment by jguterl** [comment]
Yes but it is raised a  general issue of compatibility with established
workflow. I would say having a switch to turn on/off the objectification of
the units would be nice but seems not possible due to the way module are
loaded once for all in a python session.

**Comment by dw61** [comment]
I see. But I think one of the reasons I included units is to double check we are doing valid quantity operations, e.g. the code will raise error if adding `kg` to `m`. I can definitely see that you might want accessing the float value of a quantity without changing the code, but I think maybe that's not the intended functionality of this module. Feel free to edit it in the forked repo though!

**Comment by jguterl** [comment]
Fair enough.

**Comment by dw61** [comment]
thanks for using though!

**Pull request closed without merging**
